# Configuration for the Taxon Concept Schema (TCS) standard.
metadata:
  title: "Taxon Concept Schema (TCS)"
  acronym: "tcs"
  links:
    taskGroup: "https://www.tdwg.org/community/tnc/tcs2/"
    landingPage: "https://github.com/tdwg/tcs"
    githubRepository: "https://github.com/tdwg/tcs2"

routes:
  - path: "/"
    name: "home"
    template: "home.html"
    content_md: "md/home-content.md"
